// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyWebAPI_APP.Data;

#nullable disable

namespace MyWebAPI_APP.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20220802170228_AddBillSchema")]
    partial class AddBillSchema
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("MyWebAPI_APP.Data.Bill", b =>
                {
                    b.Property<Guid>("IdBill")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("BookingDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<string>("DeliveryAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DeliveryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("NameCustomer")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("IdBill");

                    b.ToTable("Bill", (string)null);
                });

            modelBuilder.Entity("MyWebAPI_APP.Data.BillInfor", b =>
                {
                    b.Property<Guid>("IdBill")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdProduct")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Counts")
                        .HasColumnType("int");

                    b.Property<byte>("Discount")
                        .HasColumnType("tinyint");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("IdBill", "IdProduct");

                    b.HasIndex("IdProduct");

                    b.ToTable("BillInfor", (string)null);
                });

            modelBuilder.Entity("MyWebAPI_APP.Data.Products", b =>
                {
                    b.Property<Guid>("IdProduct")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("Discount")
                        .HasColumnType("tinyint");

                    b.Property<int?>("IdType")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("IdProduct");

                    b.HasIndex("IdType");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("MyWebAPI_APP.Data.TypeProduct", b =>
                {
                    b.Property<int>("IdType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdType"), 1L, 1);

                    b.Property<string>("NameType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdType");

                    b.ToTable("TypeProduct");
                });

            modelBuilder.Entity("MyWebAPI_APP.Data.BillInfor", b =>
                {
                    b.HasOne("MyWebAPI_APP.Data.Bill", "Bill")
                        .WithMany("BillInfors")
                        .HasForeignKey("IdBill")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Bill_BillInfor");

                    b.HasOne("MyWebAPI_APP.Data.Products", "Products")
                        .WithMany("BillInfors")
                        .HasForeignKey("IdProduct")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Product_BillInfor");

                    b.Navigation("Bill");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("MyWebAPI_APP.Data.Products", b =>
                {
                    b.HasOne("MyWebAPI_APP.Data.TypeProduct", "TypeProduct")
                        .WithMany("Products")
                        .HasForeignKey("IdType");

                    b.Navigation("TypeProduct");
                });

            modelBuilder.Entity("MyWebAPI_APP.Data.Bill", b =>
                {
                    b.Navigation("BillInfors");
                });

            modelBuilder.Entity("MyWebAPI_APP.Data.Products", b =>
                {
                    b.Navigation("BillInfors");
                });

            modelBuilder.Entity("MyWebAPI_APP.Data.TypeProduct", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
